project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  author: "Gabby Giacomangeli"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - Joins.qmd
    - Factors.qmd
    - Shapefiles.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    execute:
      echo: true
  

editor: visual

